version: "3.8"

services:
  backend:
    build:
      context: ./backend_RAG
      dockerfile: Dockerfile
    container_name: backend_rag
    ports:
      - "5001:5000" # Map host port 5001 to container port 5000
    volumes:
      - ./backend_RAG:/app
      - /app/venv
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/Google-service-account-credential.json
    networks:
      - medical_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/venv
    depends_on:
      - backend
    networks:
      - medical_network
    stdin_open: true
    tty: true
    # command: sh -c "python3 main.py"

networks:
  medical_network:
    driver: bridge
